{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "17334516",
   "metadata": {},
   "outputs": [],
   "source": [
    "import duckdb\n",
    "\n",
    "conn = duckdb.connect(database='madang.db')\n",
    "conn.sql(\"create table Customer as select * from 'Customer_madang.csv'\")\n",
    "conn.sql(\"create table Book as select * from 'Book_madang.csv'\")\n",
    "conn.sql(\"create table Orders as select * from 'Orders_madang.csv'\")\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "97bfd337",
   "metadata": {},
   "outputs": [],
   "source": [
    "import duckdb\n",
    "conn = duckdb.connect(database='madang.db')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "0b813eb4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "┌────────┬─────────┬─────────────────┬───────────────┐\n",
       "│ custid │  name   │     address     │     phone     │\n",
       "│ int64  │ varchar │     varchar     │    varchar    │\n",
       "├────────┼─────────┼─────────────────┼───────────────┤\n",
       "│      1 │ 박지성  │ 영국 맨체스타   │ 000-5000-0001 │\n",
       "│      2 │ 김연아  │ 대한민국 서울   │ 000-6000-0001 │\n",
       "│      3 │ 장미란  │ 대한민국 강원도 │ 000-7000-0001 │\n",
       "│      4 │ 추신수  │ 미국 클리블랜드 │ 000-8000-0001 │\n",
       "│      5 │ 박세리  │ 대한민국 대전   │ NULL          │\n",
       "└────────┴─────────┴─────────────────┴───────────────┘"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "conn.sql(\"select * from Customer\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bc910cf2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[(1, '축구의 역사', '굿스포츠', 7000),\n",
       " (2, '축구아는 여자', '나무수', 13000),\n",
       " (3, '축구의 이해', '대한미디어', 22000),\n",
       " (4, '골프 바이블', '대한미디어', 35000),\n",
       " (5, '피겨 교본', '굿스포츠', 8000),\n",
       " (6, '역도 단계별기술', '굿스포츠', 6000),\n",
       " (7, '야구의 추억', '이상미디어', 20000),\n",
       " (8, '야구를 부탁해', '이상미디어', 13000),\n",
       " (9, '올림픽 이야기', '삼성당', 7500),\n",
       " (10, 'Olympic Champions', 'Pearson', 13000)]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def query(sql, retunrType='df'):\n",
    "       if retunrType == 'df':\n",
    "              return conn.execute(sql).df()\n",
    "       else:\n",
    "              return conn.execute(sql).fetchall()\n",
    "\n",
    "#query(\"select * from Book\", \"df\")\n",
    "query(\"select * from Book\", \"list\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "6c9caf4e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[(1, 1, 1, 6000, datetime.date(2014, 7, 1)),\n",
       " (2, 1, 3, 21000, datetime.date(2014, 7, 3)),\n",
       " (3, 2, 5, 8000, datetime.date(2014, 7, 3)),\n",
       " (4, 3, 6, 6000, datetime.date(2014, 7, 4)),\n",
       " (5, 4, 7, 20000, datetime.date(2014, 7, 5)),\n",
       " (6, 1, 2, 12000, datetime.date(2014, 7, 7)),\n",
       " (7, 4, 8, 13000, datetime.date(2014, 7, 7)),\n",
       " (8, 3, 10, 12000, datetime.date(2014, 7, 8)),\n",
       " (9, 2, 10, 7000, datetime.date(2014, 7, 9)),\n",
       " (10, 3, 8, 13000, datetime.date(2014, 7, 10)),\n",
       " (11, 1, 1, 7000, datetime.date(2025, 11, 8)),\n",
       " (12, 1, 4, 8000, datetime.date(2025, 11, 8)),\n",
       " (13, 1, 10, 7000, datetime.date(2025, 11, 8))]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "conn.execute(\"select * from Orders\").fetchall()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e70f90b9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "┌─────────┬────────┬────────┬───────────┬────────────┐\n",
       "│ orderid │ custid │ bookid │ saleprice │ orderdate  │\n",
       "│  int64  │ int64  │ int64  │   int64   │    date    │\n",
       "├─────────┼────────┼────────┼───────────┼────────────┤\n",
       "│       1 │      1 │      1 │      6000 │ 2014-07-01 │\n",
       "│       2 │      1 │      3 │     21000 │ 2014-07-03 │\n",
       "│       3 │      2 │      5 │      8000 │ 2014-07-03 │\n",
       "│       4 │      3 │      6 │      6000 │ 2014-07-04 │\n",
       "│       5 │      4 │      7 │     20000 │ 2014-07-05 │\n",
       "│       6 │      1 │      2 │     12000 │ 2014-07-07 │\n",
       "│       7 │      4 │      8 │     13000 │ 2014-07-07 │\n",
       "│       8 │      3 │     10 │     12000 │ 2014-07-08 │\n",
       "│       9 │      2 │     10 │      7000 │ 2014-07-09 │\n",
       "│      10 │      3 │      8 │     13000 │ 2014-07-10 │\n",
       "│      11 │      1 │      1 │      7000 │ 2025-11-08 │\n",
       "├─────────┴────────┴────────┴───────────┴────────────┤\n",
       "│ 11 rows                                  5 columns │\n",
       "└────────────────────────────────────────────────────┘"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "conn.sql(\"select * from Orders\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "c2177ea3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>custid</th>\n",
       "      <th>name</th>\n",
       "      <th>address</th>\n",
       "      <th>phone</th>\n",
       "      <th>orderid</th>\n",
       "      <th>custid_1</th>\n",
       "      <th>bookid</th>\n",
       "      <th>saleprice</th>\n",
       "      <th>orderdate</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>박지성</td>\n",
       "      <td>영국 맨체스타</td>\n",
       "      <td>000-5000-0001</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>6000</td>\n",
       "      <td>2014-07-01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>박지성</td>\n",
       "      <td>영국 맨체스타</td>\n",
       "      <td>000-5000-0001</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>21000</td>\n",
       "      <td>2014-07-03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>김연아</td>\n",
       "      <td>대한민국 서울</td>\n",
       "      <td>000-6000-0001</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>8000</td>\n",
       "      <td>2014-07-03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>장미란</td>\n",
       "      <td>대한민국 강원도</td>\n",
       "      <td>000-7000-0001</td>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>6</td>\n",
       "      <td>6000</td>\n",
       "      <td>2014-07-04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>추신수</td>\n",
       "      <td>미국 클리블랜드</td>\n",
       "      <td>000-8000-0001</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>7</td>\n",
       "      <td>20000</td>\n",
       "      <td>2014-07-05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>1</td>\n",
       "      <td>박지성</td>\n",
       "      <td>영국 맨체스타</td>\n",
       "      <td>000-5000-0001</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>12000</td>\n",
       "      <td>2014-07-07</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>4</td>\n",
       "      <td>추신수</td>\n",
       "      <td>미국 클리블랜드</td>\n",
       "      <td>000-8000-0001</td>\n",
       "      <td>7</td>\n",
       "      <td>4</td>\n",
       "      <td>8</td>\n",
       "      <td>13000</td>\n",
       "      <td>2014-07-07</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>3</td>\n",
       "      <td>장미란</td>\n",
       "      <td>대한민국 강원도</td>\n",
       "      <td>000-7000-0001</td>\n",
       "      <td>8</td>\n",
       "      <td>3</td>\n",
       "      <td>10</td>\n",
       "      <td>12000</td>\n",
       "      <td>2014-07-08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>2</td>\n",
       "      <td>김연아</td>\n",
       "      <td>대한민국 서울</td>\n",
       "      <td>000-6000-0001</td>\n",
       "      <td>9</td>\n",
       "      <td>2</td>\n",
       "      <td>10</td>\n",
       "      <td>7000</td>\n",
       "      <td>2014-07-09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>3</td>\n",
       "      <td>장미란</td>\n",
       "      <td>대한민국 강원도</td>\n",
       "      <td>000-7000-0001</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "      <td>8</td>\n",
       "      <td>13000</td>\n",
       "      <td>2014-07-10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>1</td>\n",
       "      <td>박지성</td>\n",
       "      <td>영국 맨체스타</td>\n",
       "      <td>000-5000-0001</td>\n",
       "      <td>11</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>7000</td>\n",
       "      <td>2025-11-08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>1</td>\n",
       "      <td>박지성</td>\n",
       "      <td>영국 맨체스타</td>\n",
       "      <td>000-5000-0001</td>\n",
       "      <td>12</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>8000</td>\n",
       "      <td>2025-11-08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>1</td>\n",
       "      <td>박지성</td>\n",
       "      <td>영국 맨체스타</td>\n",
       "      <td>000-5000-0001</td>\n",
       "      <td>13</td>\n",
       "      <td>1</td>\n",
       "      <td>10</td>\n",
       "      <td>7000</td>\n",
       "      <td>2025-11-08</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    custid name   address          phone  orderid  custid_1  bookid  \\\n",
       "0        1  박지성   영국 맨체스타  000-5000-0001        1         1       1   \n",
       "1        1  박지성   영국 맨체스타  000-5000-0001        2         1       3   \n",
       "2        2  김연아   대한민국 서울  000-6000-0001        3         2       5   \n",
       "3        3  장미란  대한민국 강원도  000-7000-0001        4         3       6   \n",
       "4        4  추신수  미국 클리블랜드  000-8000-0001        5         4       7   \n",
       "5        1  박지성   영국 맨체스타  000-5000-0001        6         1       2   \n",
       "6        4  추신수  미국 클리블랜드  000-8000-0001        7         4       8   \n",
       "7        3  장미란  대한민국 강원도  000-7000-0001        8         3      10   \n",
       "8        2  김연아   대한민국 서울  000-6000-0001        9         2      10   \n",
       "9        3  장미란  대한민국 강원도  000-7000-0001       10         3       8   \n",
       "10       1  박지성   영국 맨체스타  000-5000-0001       11         1       1   \n",
       "11       1  박지성   영국 맨체스타  000-5000-0001       12         1       4   \n",
       "12       1  박지성   영국 맨체스타  000-5000-0001       13         1      10   \n",
       "\n",
       "    saleprice  orderdate  \n",
       "0        6000 2014-07-01  \n",
       "1       21000 2014-07-03  \n",
       "2        8000 2014-07-03  \n",
       "3        6000 2014-07-04  \n",
       "4       20000 2014-07-05  \n",
       "5       12000 2014-07-07  \n",
       "6       13000 2014-07-07  \n",
       "7       12000 2014-07-08  \n",
       "8        7000 2014-07-09  \n",
       "9       13000 2014-07-10  \n",
       "10       7000 2025-11-08  \n",
       "11       8000 2025-11-08  \n",
       "12       7000 2025-11-08  "
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "query(\"select * from Customer c, Orders o where c.custid = o.custid\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cd1a28e9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
